# -*- coding: utf-8 -*-
"""DL-CW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3jnnM4bmHN1KAN1rSrmFPFd7DDQMGXJ
"""

import cv2
import numpy as np
import os

from google.colab import drive
drive.mount('/content/gdrive')

# import cv2
# import numpy as np

# # Create a VideoCapture object and read from input file
# # If the input is the camera, pass 0 instead of the video file name
# cap = cv2.VideoCapture('gdrive/MyDrive/production ID_4272655.mp4')

# # Check if camera opened successfully
# if (cap.isOpened()== False): 
#   print("Error opening video stream or file")

# # Read until video is completed
# while(cap.isOpened()):
#   # Capture frame-by-frame
#   ret, frame = cap.read()
#   if ret == True:

#     # Display the resulting frame
#     cv2.imshow('Frame',frame)

#     # Press Q on keyboard to  exit
#     if cv2.waitKey(25) & 0xFF == ord('q'):
#       break

#   # Break the loop
#   else: 
#     break

# # When everything done, release the video capture object
# cap.release()

# # Closes all the frames
# cv2.destroyAllWindows()

cap = cv2.VideoCapture('gdrive/MyDrive/pexels-cottonbro-7181820.mp4')
if (cap.isOpened()== False): 
  print("Error opening video stream or file")
while True:
    ret, frame = cap.read()
    if ret == True:
      x = np.array(frame)
    else:
      break
cap.release()
cv2.destroyAllWindows()
print(x)

np.shape(x)

def resize_video(path , filename, new_path):
  # create a new folder
  cap = cv2.VideoCapture(path+filename)
  new_path_file = os.makedirs(new_path)
  fourcc = cv2.VideoWriter_fourcc(*'XVID')
  out = cv2.VideoWriter(new_path_file+'1'+filename ,fourcc, 5, (256, 256))
  
  if (cap.isOpened()== False): 
    print("Error opening video stream or file")
  while True:
      ret, frame = cap.read()
      if ret == True:
          b = cv2.resize(frame,(256, 256),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
          out.write(b)
      else:
          break
      
  cap.release()
  out.release()
  cv2.destroyAllWindows()

# path = 'gdrive/MyDrive/Taichi/train'
# for files in os.listdir(path):
#  print( files)

# resize_video('gdrive/MyDrive/','pexels-cottonbro-7181820.mp4')

def A(new_path):
  count=0
  cap = cv2.VideoCapture(new_path)
  if (cap.isOpened()== False): 
    print("Error opening video stream or file")
  while True:
      ret, frame = cap.read()
      count+=1
      if count == 1:
        x_s = np.array(frame)
      else:
        x_d = np.array(frame)
  cap.release()
  cv2.destroyAllWindows()
  return x_s,x_d

def frame_to_video(frame):

path = 'gdrive/MyDrive/Taichi/train/'
new_path='gdrive/MyDrive/Taichi/resized_videos_train/'
for files in os.listdir(path):
  resize_video(path, files, new_path)

def main():
  path = 'gdrive/MyDrive/Taichi/train'
  new_path='gdrive/MyDrive/Taichi/resized_videos_train/'
  for files in os.listdir(path):
    resize_video(path, files, new_path)
  
  for files in os.listdir(new_path):
    x_s, x_d =  A(new_path)
        
  
if __name__ == "__main__":
  main()