#Copyright Snap Inc. 2021. This sample code is made available by Snap Inc. for informational purposes only.
#No license, whether implied or otherwise, is granted in or to such code (including any rights to copy, modify,
#publish, distribute and/or commercialize such code), unless you have entered into a separate agreement for such rights.
#Such code is provided as-is, without warranty of any kind, express or implied, including any warranties of merchantability,
#title, fitness for a particular purpose, non-infringement, or that such code is free of defects, errors or viruses.
#In no event will Snap Inc. be liable for any damages or losses of any kind arising from the sample code or your use thereof.


dataset_params:
  root_dir: data/taichi-png

train_params:
  num_epochs: 100
  num_repeats: 150
  epoch_milestones: [60, 90]
  lr: 2.0e-4
  batch_size: 14
  dataloader_workers: 6
  checkpoint_freq: 50
  scales: [1, 0.5, 0.25, 0.125]
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]
    equivariance_shift: 10
    equivariance_affine: 10
